/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.File;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import koneksi.db;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ACER
 */
public class view_report extends javax.swing.JFrame {

    /**
     * Creates new form LapAnggota
     */
    public view_report() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JLabel();
        btn_anggota = new javax.swing.JLabel();
        btn_buku = new javax.swing.JLabel();
        btn_sirkulasi = new javax.swing.JLabel();
        bgbg = new javax.swing.JLabel();

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg_menu.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_anggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_anggota.png"))); // NOI18N
        btn_anggota.setText("jLabel1");
        btn_anggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_anggotaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_anggotaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_anggotaMouseExited(evt);
            }
        });
        getContentPane().add(btn_anggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 250, 120));

        btn_buku.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_buku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_buku.png"))); // NOI18N
        btn_buku.setText("BUKU");
        btn_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_bukuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_bukuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_bukuMouseExited(evt);
            }
        });
        getContentPane().add(btn_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 250, 120));

        btn_sirkulasi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_sirkulasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_sirkulasi.png"))); // NOI18N
        btn_sirkulasi.setText("PEMINJAMAN");
        btn_sirkulasi.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn_sirkulasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_sirkulasiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_sirkulasiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_sirkulasiMouseExited(evt);
            }
        });
        getContentPane().add(btn_sirkulasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 250, 120));

        bgbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg_menu.png"))); // NOI18N
        getContentPane().add(bgbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_anggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_anggotaMouseClicked
        try {
            db koneksi = new db();
            koneksi.connect();
            try {
                Map<String, Object> parameter = new HashMap<String, Object>();
                
                File rpt = new File("src/Report/LepAnggota.jrxml");
                JasperDesign jasDesign = JRXmlLoader.load(rpt);
                parameter.clear();
                JasperReport jasReport = JasperCompileManager.compileReport(jasDesign);
                JasperPrint jasPrint = JasperFillManager.fillReport(jasReport,
                        parameter, koneksi.connect());
                JasperViewer.viewReport(jasPrint, false);
            } catch (JRException a) {
                JOptionPane.showMessageDialog(null, "Laporan tidak ditemukan" + a);
            }
        } catch (Exception a) {
            JOptionPane.showMessageDialog(null, a);
        }
    }//GEN-LAST:event_btn_anggotaMouseClicked

    private void btn_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bukuMouseClicked
        try {
            db koneksi = new db();
            koneksi.connect();
            try {
                Map<String, Object> parameter = new HashMap<String, Object>();

                File rpt = new File("src/Report/LepBuku.jrxml");
                JasperDesign jasDesign = JRXmlLoader.load(rpt);
                parameter.clear();
                JasperReport jasReport = JasperCompileManager.compileReport(jasDesign);
                JasperPrint jasPrint = JasperFillManager.fillReport(jasReport,
                        parameter, koneksi.connect());
                JasperViewer.viewReport(jasPrint, false);
            } catch (JRException a) {
                JOptionPane.showMessageDialog(null, "Laporan tidak ditemukan" + a);
            }
        } catch (Exception a) {
            JOptionPane.showMessageDialog(null, a);
        }

    }//GEN-LAST:event_btn_bukuMouseClicked

    private void btn_sirkulasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sirkulasiMouseClicked
        try {
            db koneksi = new db();
            koneksi.connect();
            try {
                Map<String, Object> parameter = new HashMap<String, Object>();

                File rpt = new File("src/Report/LepPeminjaman.jrxml");
                JasperDesign jasDesign = JRXmlLoader.load(rpt);
                parameter.clear();
                JasperReport jasReport = JasperCompileManager.compileReport(jasDesign);
                JasperPrint jasPrint = JasperFillManager.fillReport(jasReport,
                        parameter, koneksi.connect());
                JasperViewer.viewReport(jasPrint, false);
            } catch (JRException a) {
                JOptionPane.showMessageDialog(null, "Laporan tidak ditemukan" + a);
            }
        } catch (Exception a) {
            JOptionPane.showMessageDialog(null, a);
        }

    }//GEN-LAST:event_btn_sirkulasiMouseClicked

    private void btn_sirkulasiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sirkulasiMouseEntered
        btn_sirkulasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_sirkulasi_hover.png")));    // TODO add your handling code here:
    }//GEN-LAST:event_btn_sirkulasiMouseEntered

    private void btn_sirkulasiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sirkulasiMouseExited
        btn_sirkulasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_sirkulasi.png")));    // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_sirkulasiMouseExited

    private void btn_anggotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_anggotaMouseEntered
        btn_anggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_anggota_hover.png")));    // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_btn_anggotaMouseEntered

    private void btn_anggotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_anggotaMouseExited
        btn_anggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_anggota.png")));    // TODO add your handling code here:        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_btn_anggotaMouseExited

    private void btn_bukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bukuMouseEntered
        btn_buku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_buku_hover.png")));    // TODO add your handling code here:        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_btn_bukuMouseEntered

    private void btn_bukuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bukuMouseExited
        btn_buku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_buku.png")));    // TODO add your handling code here:        // TODO add your handling code here:        // TODO add your handling code here:        
// TODO add your handling code here:
    }//GEN-LAST:event_btn_bukuMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bgbg;
    private javax.swing.JLabel btn_anggota;
    private javax.swing.JLabel btn_buku;
    private javax.swing.JLabel btn_sirkulasi;
    // End of variables declaration//GEN-END:variables
}
