/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.awt.Color;
import entity.ent_buku;
import factory.factory;
import interfaces.int_buku;
import java.util.List;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
/**
 * 
 *
 * @author xzan
 */
public class view_buku extends javax.swing.JFrame {

    private int baris;
    private String proses;
    private boolean status;
    private DefaultTableModel dtmbk;
    private String[] tabelHeader;
    private int_buku bukuDAO;
    private List<ent_buku> listBuku;
    private ent_buku b;
    
    private void enable_text(boolean status) {
        judul.setEditable(status);  
	kategori.setEditable(status);  
	penerbit.setEnabled(status);  
	stok.setEnabled(status);  
        tbl_buku.setEnabled(!status);
    }

    private void refreshIsiTabel() {
       listBuku = bukuDAO.getBuku(cari.getText());
       dtmbk = (DefaultTableModel) tbl_buku.getModel();
       dtmbk.setRowCount(0);

        for(ent_buku data : listBuku) {
            dtmbk.addRow(new Object[] {
              data.getJudul(),
              data.getKategori(), 
              data.getPenerbit(), 
              data.getStok()
            });
         }
               
       if (tbl_buku.getRowCount() > 0) {
	baris = tbl_buku.getRowCount() -1;
	tbl_buku.setRowSelectionInterval (baris, baris);
	
	proses = "";
        }

    }
    
        public view_buku() {
        initComponents();
            enable_text(false);
//        btn_edit.setVisible(false);
//        btn_tambah.setVisible(false);
          btn_cancel.setVisible(false);
          btn_save.setVisible(false);
          
          bukuDAO = factory.getBukuDA0();
          tabelHeader = new String[] {"Judul", "Kategori", "Penerbit", "Stok"};
          dtmbk = new DefaultTableModel (null, tabelHeader);
          tbl_buku.setModel(dtmbk);
          tbl_buku.getSelectionModel().addListSelectionListener( new ListSelectionListener() {

          public void valueChanged(ListSelectionEvent e) {
            baris = tbl_buku.getSelectedRow();
            if (baris >= 0) {
		judul.setText(dtmbk.getValueAt(baris, 0) .toString()); 
		penerbit.setText(dtmbk.getValueAt(baris, 1) .toString());
		kategori.setText(dtmbk.getValueAt (baris, 2) .toString());
                stok.setText(dtmbk.getValueAt (baris, 3) .toString());
	
                }
            }
           });
        
          refreshIsiTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kategori = new javax.swing.JTextField();
        stok = new javax.swing.JTextField();
        btn_save = new javax.swing.JLabel();
        btn_tambah = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JLabel();
        btn_edit = new javax.swing.JLabel();
        btn_refresh = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JLabel();
        tbl_anggota = new javax.swing.JScrollPane();
        tbl_buku = new javax.swing.JTable();
        judul = new javax.swing.JTextField();
        penerbit = new javax.swing.JTextField();
        cari = new javax.swing.JTextField();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 620));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kategori.setBackground(new Color(0,0,0,0));
        kategori.setFont(new java.awt.Font("Osaka", 0, 20)); // NOI18N
        kategori.setForeground(new java.awt.Color(128, 128, 128));
        kategori.setBorder(null);
        kategori.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        kategori.setSelectionColor(new java.awt.Color(0, 122, 255));
        getContentPane().add(kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 450, 220, 30));

        stok.setBackground(new Color(0,0,0,0));
        stok.setFont(new java.awt.Font("Osaka", 0, 20)); // NOI18N
        stok.setForeground(new java.awt.Color(128, 128, 128));
        stok.setBorder(null);
        stok.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        stok.setSelectionColor(new java.awt.Color(0, 122, 255));
        getContentPane().add(stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 518, 220, 30));

        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_save.png"))); // NOI18N
        btn_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_saveMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_saveMouseEntered(evt);
            }
        });
        getContentPane().add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 186, 60, -1));

        btn_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_tambah.png"))); // NOI18N
        btn_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambahMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_tambahMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_tambahMouseEntered(evt);
            }
        });
        getContentPane().add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 186, 60, -1));

        btn_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_cancel.png"))); // NOI18N
        btn_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cancelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_cancelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cancelMouseEntered(evt);
            }
        });
        getContentPane().add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 266, 60, -1));

        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_edit.png"))); // NOI18N
        btn_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editMouseEntered(evt);
            }
        });
        getContentPane().add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 266, 60, -1));

        btn_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_refresh.png"))); // NOI18N
        btn_refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_refreshMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_refreshMouseEntered(evt);
            }
        });
        getContentPane().add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 426, 60, -1));

        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_delete.png"))); // NOI18N
        btn_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_hapusMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_hapusMouseEntered(evt);
            }
        });
        getContentPane().add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 346, 60, -1));

        tbl_anggota.setBackground(new java.awt.Color(102, 255, 102));
        tbl_anggota.setBorder(null);
        tbl_anggota.setForeground(new java.awt.Color(204, 51, 255));

        tbl_buku.setForeground(new java.awt.Color(51, 51, 51));
        tbl_buku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"TEST", "TEST", null, null},
                {"TEST", "TEST", null, null},
                {"TEST", "TEST", null, null},
                {null, "TEST", null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_buku.setSelectionBackground(new java.awt.Color(0, 122, 255));
        tbl_buku.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tbl_anggota.setViewportView(tbl_buku);

        getContentPane().add(tbl_anggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 480, 205));

        judul.setBackground(new Color(0,0,0,0));
        judul.setFont(new java.awt.Font("Osaka", 0, 20)); // NOI18N
        judul.setForeground(new java.awt.Color(128, 128, 128));
        judul.setBorder(null);
        judul.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        judul.setSelectionColor(new java.awt.Color(0, 122, 255));
        getContentPane().add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 450, 220, 30));

        penerbit.setBackground(new Color(0,0,0,0));
        penerbit.setFont(new java.awt.Font("Osaka", 0, 20)); // NOI18N
        penerbit.setForeground(new java.awt.Color(128, 128, 128));
        penerbit.setBorder(null);
        penerbit.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        penerbit.setSelectionColor(new java.awt.Color(0, 122, 255));
        getContentPane().add(penerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 518, 220, 30));

        cari.setBackground(new Color(0,0,0,0));
        cari.setFont(new java.awt.Font("Osaka", 0, 18)); // NOI18N
        cari.setForeground(new java.awt.Color(255, 255, 255));
        cari.setBorder(null);
        cari.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        cari.setSelectionColor(new java.awt.Color(0, 84, 129));
        cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariKeyReleased(evt);
            }
        });
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 80, 165, 30));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg_bubku.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseExited
        btn_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_tambah.png")));
    }//GEN-LAST:event_btn_tambahMouseExited

    private void btn_tambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseEntered
        btn_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_tambah_hover.png")));
    }//GEN-LAST:event_btn_tambahMouseEntered

    private void btn_hapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseExited
        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_delete.png")));
    }//GEN-LAST:event_btn_hapusMouseExited

    private void btn_editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseExited
        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_edit.png")));
    }//GEN-LAST:event_btn_editMouseExited

    private void btn_editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseEntered
        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_edit_hover.png")));
    }//GEN-LAST:event_btn_editMouseEntered

    private void btn_hapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseEntered
        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_delete_hover.png")));
    }//GEN-LAST:event_btn_hapusMouseEntered

    private void btn_refreshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_refreshMouseExited
        btn_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_refresh.png")));
    }//GEN-LAST:event_btn_refreshMouseExited

    private void btn_refreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_refreshMouseEntered
        btn_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_refresh_hover.png")));
    }//GEN-LAST:event_btn_refreshMouseEntered

    private void btn_saveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMouseExited
        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_save.png")));
    }//GEN-LAST:event_btn_saveMouseExited

    private void btn_saveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMouseEntered
        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_save_hover.png")));
    }//GEN-LAST:event_btn_saveMouseEntered

    private void btn_cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelMouseExited
        btn_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_cancel.png")));
    }//GEN-LAST:event_btn_cancelMouseExited

    private void btn_cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelMouseEntered
        btn_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_cancel_hover.png")));
    }//GEN-LAST:event_btn_cancelMouseEntered

    private void btn_tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseClicked
        btn_tambah.setVisible(false);
        btn_edit.setVisible(false);
        btn_hapus.setVisible(false);
        btn_refresh.setVisible(false);
        
        btn_save.setVisible(true);
        btn_cancel.setVisible(true);
        enable_text(true);
        
        judul.setText("");
        kategori.setText("");
        penerbit.setText("");
        stok.setText("");
    }//GEN-LAST:event_btn_tambahMouseClicked

    private void btn_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseClicked
        btn_tambah.setVisible(false);
        btn_edit.setVisible(false);
        btn_hapus.setVisible(false);
        btn_refresh.setVisible(false);
        
        btn_save.setVisible(true);
        btn_cancel.setVisible(true); 
        enable_text(true);
    }//GEN-LAST:event_btn_editMouseClicked

    private void btn_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelMouseClicked
        btn_tambah.setVisible(true);
        btn_edit.setVisible(true);
        btn_hapus.setVisible(true);
        btn_refresh.setVisible(true);
        
        btn_save.setVisible(false);
        btn_cancel.setVisible(false);
        enable_text(false);
        
        refreshIsiTabel();
    }//GEN-LAST:event_btn_cancelMouseClicked

    private void cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKeyReleased
        refreshIsiTabel();
    }//GEN-LAST:event_cariKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_buku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btn_cancel;
    private javax.swing.JLabel btn_edit;
    private javax.swing.JLabel btn_hapus;
    private javax.swing.JLabel btn_refresh;
    private javax.swing.JLabel btn_save;
    private javax.swing.JLabel btn_tambah;
    private javax.swing.JTextField cari;
    private javax.swing.JTextField judul;
    private javax.swing.JTextField kategori;
    private javax.swing.JTextField penerbit;
    private javax.swing.JTextField stok;
    private javax.swing.JScrollPane tbl_anggota;
    private javax.swing.JTable tbl_buku;
    // End of variables declaration//GEN-END:variables
}
